service: forecast-api
frameworkVersion: '2'
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    REGION: ${aws:region}
    STORMGLASS_API_URL: ${env:STORMGLASS_API_URL}
    STORMGLASS_API_AUTH: ${env:STORMGLASS_API_AUTH}

custom:
  bundle:
    tsConfig: '../../tsconfig.json'
  serverless-offline-ssm:
    stages:
      - dev

functions:
  getForecast:
    handler: src/stormGlass/handler.stormGlass
    events:
      - http:
          path: /forecast
          method: get
          cors: true

plugins:
  - serverless-offline-ssm
  - serverless-offline
  - serverless-bundle
  - serverless-localstack
